import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  experimental: { optimizePackageImports: ["framer-motion"] },

  async redirects() {
    return [
      // The game was "the descent" until the Vault became a tower. Anything
      // already bookmarked or installed still points here.
      { source: "/descent", destination: "/climb", permanent: true },
    ];
  },

  async rewrites() {
    return [
      /**
       * Android checks https://<domain>/.well-known/assetlinks.json to decide
       * whether the installed app really belongs to this site. Next refuses to
       * serve anything from a dot-directory inside public/, so the file lives at
       * the root and is exposed here under the path Android insists on.
       *
       * Without this the app still runs — with a browser address bar across the
       * top, which is precisely what installing it was meant to remove.
       */
      { source: "/.well-known/assetlinks.json", destination: "/assetlinks.json" },

      // Farcaster reads the Mini App manifest from the same kind of path. It is
      // generated by a route because the ownership signature lives in env vars.
      { source: "/.well-known/farcaster.json", destination: "/api/farcaster/manifest" },
    ];
  },
};

export default nextConfig;
