-- AlterTable
ALTER TABLE "IdleItem" ADD COLUMN     "vitality" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "IdleProfile" ADD COLUMN     "defeats" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hp" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "recoverFor" DOUBLE PRECISION NOT NULL DEFAULT 0;
