-- AlterTable
ALTER TABLE "IdleProfile" ADD COLUMN     "lastRoarAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastStrikeAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "rebirths" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "relics" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "relicsEarned" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "relicsJson" TEXT NOT NULL DEFAULT '{}';
