-- AlterTable
ALTER TABLE "IdleProfile" ADD COLUMN     "autoSellBelow" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "lastBreathAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "shieldFor" DOUBLE PRECISION NOT NULL DEFAULT 0;
