-- AlterTable
ALTER TABLE "IdleProfile" ADD COLUMN     "boostKey" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "boostUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "boostsJson" TEXT NOT NULL DEFAULT '{}',
ADD COLUMN     "calendarCycle" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "calendarDay" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "calendarDayKey" TEXT NOT NULL DEFAULT '';
